### ISSUE TITLE
Meta issue for syntax improvements in Pulse

### ISSUE THREAD

**Issue by aseemr** [FStarLang/steel#139]
- [ ] `fn (p:int -> int) ...` doesn't parse, it has to be written as `fn (p:(int -> int)) ...` (note the extra parenthesis around the arrow)
- [ ] `let _ : t = e;` doesn't parse, it has to be written as `let _u : t = e`
- [ ] refinement types annotation `x:int { p x }` doesn't work, it has to be written as `x:(x:int { p x })`

**Comment by nikswamy** [comment]
Fixed in 5c18b713a891323d828a5591fd6e2c7c4f00af16
